repos:
  - id: '/.*/'
    apply_requirements:
      - mergeable
    allowed_overrides:
      - workflow # Allow repos to select a different workflow from default
      - apply_requirements
    allow_custom_workflows: false
metrics:
  prometheus:
    endpoint: /metrics
policies:
  conftest_version: 0.38.0
  owners:
    users:
      - albertorm95
  policy_sets: []
